[phases.setup]
nixPkgs = ["nodejs", "python3", "gcc", "gnumake", "pkg-config"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "node setup-db.js"]

[start]
cmd = "node dist/app.js"
